### Listar todas as tarefas
GET http://localhost:5000/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Testando",
    "descricao": "Testando",
    "categoriaId": "aa93f312-4545-429b-bfec-641a3e376882"
}

### Alterar uma tarefa
PUT http://localhost:5000/tarefas/alterar/2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e

### Listar tarefas não concluídas
GET http://localhost:5000/tarefas/naoconcluidas

### Listar tarefas concluídas
GET http://localhost:5000/tarefas/concluidas
